# Backend (Intel best option)
backend = "egl";

vsync = true;
vsync-method = "drm";

use-damage = false;
unredir-if-possible = false;

corner-radius = 10;

detect-rounded-corners = true;
detect-client-opacity = true;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
];
