# Change Ctrl+b to Ctrl+a key binding
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Set path variable
set-option -g update-environment "PATH"

# Act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Throwing this in because neovim is showing some warning
set-option -g focus-events on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered automatically
set-option -g renumber-windows on

# Enable true colour
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Clock mode
setw -g clock-mode-colour blue

# Pane-border
set -g pane-border-style "fg=orange,bg=default"
set -g pane-active-border-style "fg=red,bg=default"

# Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=orange'

set -g status-left ''
set -g status-left-length 10

set -g status-right ''
set -g status-right-length 0

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=black bg=orange'
setw -g window-status-format ' #I #W #F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# Reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf
